name: music_app
description: "A beautiful music player app with online and local music support."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  just_audio: ^0.9.40
  just_audio_web: ^0.4.9
  shared_preferences: ^2.3.3
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  path_provider_android: ^2.2.22
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  marquee: ^2.2.3
  audio_session: ^0.1.21
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
